### ISSUE TITLE
What is the difference between start and run goals?

### ISSUE THREAD

**Issue by niyue** [jcabi/jcabi-dynamodb-maven-plugin#62] opened 2016-11-22 14:56 UTC
I read the doc about these two goals, `start` and `run`:
http://dynamodb.jcabi.com/start-mojo.html
http://dynamodb.jcabi.com/run-mojo.html
But I couldn't understand what the exact difference is between them.

I expected the `mvn jcabi-dynamodb:run` goal to work like `mvn jetty:run`, which starts a long running daemon and doesn't quit immediately. But it turned out not to work as I expected and the dynamodb quits immediately after Maven quits.

I read through the github issues/PRs here, and found issue #35 and PR #53:
* issue #35 proposed a work around, but it didn't work for me for some reason
* it seems PR #53 is what I want but it doesn't get merged for a very long time

I wonder what is the expected behavior for the `run` goal, is it a bug for its current behavior, issue #35 a work around for this bug and PR #53 is the fix for this bug? If it is not a bug, how should we use the `run` goal? Thanks.

**Comment by dmarkov** [comment] 2016-11-28 07:56
@yegor256 please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment] 2017-04-03 16:54
@rultor release, tag is `0.8.1`

**Comment by 0crat** [comment] 2017-04-03 17:10
@yegor256 please, ask @niyue to close this issue and [read more](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html)

**Comment by 0crat** [comment] 2017-04-03 17:10
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment] 2017-04-03 17:11
@niyue I believe the problem is solved, try version 0.8.1

**Closed by yegor256** 2017-04-03 17:11 UTC
Labels: cosmetic, invalid

**Comment by yegor256** [comment] 2017-04-03 17:40
@niyue see #65 You need `wait` goal
